.TH HCRON-FQDN "1" "November 2009" "hcron 0.9" ""
.SH NAME
hcron-fqdn \- Print the fully qualified host name of the local machine
.SH SYNOPSIS
.B hcron-fqdn

.SH DESCRIPTION
hcron-fqdn returns the fully qualified host name of the local machine.
This is important since hcron events are host specific (i.e., only
those events defined under ~/.hcron/<hostName> are loaded for the
named host).

.SH SEE ALSO
hcron(7), hcron-event(1)

.SH AUTHOR
Written by John Marshall.

.SH "REPORTING BUGS"
Report bugs to <xyz@xyz>.

.SH COPYRIGHT
Copyright \(co 2008,2009 Environment Canada.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
