.TH HCRON-RELOAD "1" "November 2009" "hcron 0.9" ""
.SH NAME
hcron-reload \- Signal hcron-scheduler to reload user hcron event definition files
.SH SYNOPSIS
.B hcron-reload

.SH DESCRIPTION
hcron-reload signals to the hcron-scheduler that the user's hcron event
definition files should be reloaded. This step is necessary in order
for any changes to take effect.

.SH SEE ALSO
hcron(7), hcron-event(1), hcron-scheduler(8)

.SH AUTHOR
Written by John Marshall.

.SH "REPORTING BUGS"
Report bugs to <xyz@xyz>.

.SH COPYRIGHT
Copyright \(co 2008,2009 Environment Canada.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
