#!/bin/sh

set -e

update-rc.d hcron defaults 89 11 >/dev/null

for name in hcron.conf hcron.allow; do
	if [ ! -r /etc/hcron/${name} ]; then
		cp /etc/hcron/${name}.sample /etc/hcron/${name}
	fi
done

# /var/spool/hcron
if [ ! -d /var/spool/hcron ]; then
	mkdir -p /var/spool/hcron
fi
chmod a+rwx,o+t /var/spool/hcron

# /var/log/hcron
if [ ! -d /var/log/hcron ]; then
	mkdir -p /var/log/hcron
fi
chmod a+rx /var/log/hcron

# /var/lib/hcron
if [ ! -d /var/lib/hcron ]; then
	mkdir -p /var/lib/hcron
fi
chmod a+rx /var/lib/hcron

if [ ! -d /var/lib/hcron/event_lists ]; then
	mkdir -p /var/lib/hcron/event_lists
fi
chmod a+rx /var/lib/hcron/event_lists

if [ ! -d /var/lib/hcron/trees ]; then
	mkdir -p /var/lib/hcron/trees
fi
chmod go-rwx /var/lib/hcron/trees

# other
if [ -x /etc/init.d/hcron ]; then
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d hcron start
	else
		/etc/init.d/hcron start
	fi
fi
