.TH HCRON-SCHEDULER "8" "March 2010" "hcron 0.13" ""
.SH NAME
hcron-scheduler \- Server which schedules and executes hcron events
.SH SYNOPSIS
.B hcron-scheduler

.SH DESCRIPTION
The scheduler loads event definitions set up for the local host and
executes commands accordingly. When run by the root user, event
definitions of those users listed in the hcron.allow file are managed;
otherwise, only the events of the current user are managed. The standard
operation is to run as root.

Certain operational information is logged to a specific log file or to
the syslog service.

.SH METHOD OF OPERATION
.PP
Each minute, hcron-scheduler performs a number of checks in order to
keep up to date:

.IP \[bu] 2
A change in the modification time of the hcron.conf file forces a full
restart of the server.

.IP \[bu] 2
A change in the modification time of the hcron.allow file forces a
reload of the list of allowed users, the event information of
non-existent users is discarded, and the event definitions of new users
is loaded.

.IP \[bu] 2
The hcron spool directory is checked for files. For each file that is
found, the event information of the user name owning the file is
reloaded as appropriate.

.SH HCRON.ALLOW FILE
.PP
The hcron.allow file contains a list of all users for which hcron-scheduler
will load event definitions and schedule. Empty lines and those starting
with # are ignored.

.SH HCRON.CONF FILE
.PP
The hcron.conf file contains configuration settings for hcron-scheduler.
It takes the form of a simplified (simple object types) Python dictionary
with the following keys:

.TP
.B allowLocalhost
Boolean indicating whether or not event commands may be done on the
localhost, as specified by the host setting of the event definition.
This restriction applies to any address which resolves to the local
host.

.TP
.B commandSpawnTimeout
Maximum time allowed for a command to be spawned. This does not limit
the time allowed for a command to execute, but serves to limit spawned
processes on the hcron machine.

.TP
.B eventsBasePath
Path below which to search for user event definitions, following the
pattern <eventsBasePath>/<userName>. If undefined or None, user
definitions are loaded from the user's home (~<userName>).

.TP
.B logPath
Path of the log file, when useSyslog is False. A relative path is
prepended with /var/log.

.TP
.B maxEventsPerUser
Maximum number of events allowed per user.

.TP
.B namesToIgnoreRegexp
Regular expression matching event (and directory) names to ignore when
loading events. The default is to ignore hidden files (starting with .)
and names ending with ~ (commonly used to name backup or temporary
files when editing).

.TP
.B smtpServer
Host name of an SMTP server willing to accept connections. If not
specified, localhost is used.

.TP
.B useSyslog
Boolean indicating whether or not to send the logging information to
the syslog daemon.

.PP
As in Python, empty lines and those starting with # are ignored.

.SH HCRON SPOOL DIRECTORY
.PP
The hcron spool directory is accessible to all users within which signal
files can be created using hcron-reload. At the start of each scheduling
period, the signal files are checked. For each signal file, the event
definition files of its owner are reloaded. Then, the signal files are
removed. The worst case reload wait is just short of two scheduling periods.

.SH EXAMPLES
.PP
A default hcron.conf configuration:

.RS
.nf
# hcron.conf
{
    "allowLocalhost": False,
    "commandSpawnTimeout": 15,
    "eventsBasePath": None,
    "logPath": "hcron.log",
    "maxEventsPerUser": 25,
    "namesToIgnoreRegexp": "(\..*)|(.*~$)",
    "smtpServer": "localhost",
    "useSyslog": False,
}
.fi
.RE

.SH SIGNALS
hcron-scheduler reacts to the following signals by:
.RS
.nf
kill -<signal> `cat /var/run/hcron.pid`
.fi
.RE

.IP SIGHUP
Reload all configuration files and event definitions.

.IP SIGTERM
Terminate.

.SH FILES
.IP /etc/hcron/hcron.allow
See HCRON.ALLOW above.

.IP /etc/hcron/hcron.conf
See HCRON.CONF above.

.IP /var/lib/hcron/event_lists/<userName>
Lists the current event lists of the associated user according to the format (see hcron-reload).

.IP /var/log/hcron.log
Default location of the log file (when useSyslog is False).

.IP /var/run/hcron.pid
Pid file for the currently running hcron-scheduler. This is managed by
hcron-scheduler itself.

.SH SEE ALSO
hcron(7), hcron-event(1), hcron-reload(1)

.SH AUTHOR
Written by John Marshall.

.SH "REPORTING BUGS"
Report bugs to <xyz@xyz>.

.SH COPYRIGHT
Copyright \(co 2008-2010 Environment Canada.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
