#!/bin/sh

set -e

update-rc.d hcron defaults 89 11 >/dev/null

if [ ! -r /etc/hcron/hcron.conf ]; then
    cp /etc/hcron/hcron.conf.sample /etc/hcron/hcron.conf
fi

touch /etc/hcron/hcron.allow
chmod a+rwx,o+t /var/spool/hcron

if [ -x /etc/init.d/hcron ]; then
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d hcron start
    else
        /etc/init.d/hcron start
    fi
fi
