#!/bin/sh

set -e

update-rc.d hcron defaults 89 11 >/dev/null

for name in hcron.conf hcron.allow; do
	if [ ! -r /etc/hcron/${name} ]; then
		cp /etc/hcron/${name}.sample /etc/hcron/${name}
	fi
done

if [ -x /var/spool/hcron ]; then
	chmod a+rwx,o+t /var/spool/hcron
fi

if [ -x /etc/init.d/hcron ]; then
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d hcron start
	else
		/etc/init.d/hcron start
	fi
fi
