.TH HCRON-RELOAD "1" "November 2010" "hcron 0.17" ""
.SH NAME
hcron-reload \- Signal hcron-scheduler to reload user hcron event definition files
.SH SYNOPSIS
.B hcron-reload

.SH DESCRIPTION
hcron-reload creates a "snapshot" of the hcron event definition tree and
signals to the hcron-scheduler that it should reload the user's event
information. This step is necessary in order for any changes to take effect.

.SH FILES
.IP /var/lib/hcron/event_lists/<username>
Lists the current event lists of the associated user according to the format:

.IP /var/lib/hcron/trees/<username>
Local copy of the each user's event definition tree snapshot.

.RS
.nf
accepted::<path>
rejected:<reason>:<path>
.fi
.RE

.SH SEE ALSO
hcron(7), hcron-event(1), hcron-scheduler(8)

.SH AUTHOR
Written by John Marshall.

.SH "REPORTING BUGS"
Report bugs to: <http://code.google.com/p/hcron/>.

.SH COPYRIGHT
Copyright \(co 2008-2010 Environment Canada.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
